### ISSUE TITLE
Evaluate use of system uthash

### ISSUE THREAD

**Issue by dvershinin** [ADD-SP/ngx_waf#7]
Even quite conservative distros like CentOS 6, 7 and 8, all have uthash 2.0.2 available.

As I have checked, the module compiles just fine if I replace the include everywhere with `<uthash.h>`.

Would there be a problem to use this uthash version? 

This would simplify instructions to simply install `uthash-devel` package on RedHat-based distros,
and `uthash-dev` on Debian-based distros. 

And the resulting module file would use the system library which (potentially) receives security updates; lower mem use if something else besides this module uses the library.

**Comment by ADD-SP** [comment]
Thanks for the suggesting. Switching to a system library is a good idea. I didn't actually notice that uthash is included in the system library.

After testing, uthash 2.0.1 works fine with Ubuntu 18.04 LTS. I've updated the dev branch to switch to the system library. Just to be safe, the dev branch will be tested for a month. If there are no new problems during the testing period I will release v2.0.1 and close this issue.

**Comment by ADD-SP** [comment]
Hello, [v2.0.1](https://github.com/ADD-SP/ngx_waf/releases/tag/v2.0.1) has been released and I will close this issue. If you find any related problems later, you can reopen this issue.

**Comment by dvershinin** [comment]
Currently, it fails to compile 2.0.1 with:

```
ngx_waf-2.0.1/src/ngx_http_waf_module_core.c:3:10: fatal error: ../inc/uthash/src/uthash.h: No such file or directory
 #include "../inc/uthash/src/uthash.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
So at least in `src/ngx_http_waf_module_core.c` the reference to include is invalid still.
