### ISSUE TITLE
Failure to compile with mainline NGINX

### ISSUE THREAD

**Issue by dvershinin** [ADD-SP/ngx_waf#9]
Latest release 2.0.2 does not compile with NGINX 1.19.5. Errors:

```
In file included from ngx_waf-2.0.2/src/ngx_http_waf_module_core.c:13:
ngx_waf-2.0.2/src/../inc/ngx_http_waf_module_config.h: In function 'ngx_http_waf_create_srv_conf':
ngx_waf-2.0.2/src/../inc/ngx_http_waf_module_config.h:184:25: error: too few arguments to function 'ngx_log_init'
     srv_conf->ngx_log = ngx_log_init(NULL);
                         ^~~~~~~~~~~~
In file included from src/core/ngx_core.h:60,
                 from ngx_waf-2.0.2/src/../inc/ngx_http_waf_module_core.h:2,
                 from ngx_waf-2.0.2/src/ngx_http_waf_module_core.c:2:
src/core/ngx_log.h:231:12: note: declared here
 ngx_log_t *ngx_log_init(u_char *prefix, u_char *error_log);
            ^~~~~~~~~~~~
```

Looks like the function `ngx_log_init` has changed its signature at some point and requires a second argument on the mainline branch only (stable is fine).

**Comment by dvershinin** [comment]
Shouldn't you be using something along the lines of `"#ifdef nginx_version"` ? That constant is bumped between stable and mainline and can be used to detect backward-incompatible changes...

> #define nginx_version      1019005

In `src/core/nginx.h`. For mainline it's `1019005` and for stable it is `1018000`

The breaking change of `ngx_log_t *ngx_log_init(u_char *prefix, u_char *error_log);` was introduced only at 1.19.5 which is `1019005`, so I think it's easiest to do conditional code based on nginx_version >= 1019005 (instead of introducing another define/compilation option, just use what's there).

**Comment by ADD-SP** [comment]
> Shouldn't you be using something along the lines of `"#ifdef nginx_version"` ? That constant is bumped between stable and mainline and can be used to detect backward-incompatible changes...
> 
> > #define nginx_version      1019005
> 
> In `src/core/nginx.h`. For mainline it's `1019005` and for stable it is `1018000`
> 
> The breaking change of `ngx_log_t *ngx_log_init(u_char *prefix, u_char *error_log);` was introduced only at 1.19.5 which is `1019005`, so I think it's easiest to do conditional code based on nginx_version >= 1019005 (instead of introducing another define/compilation option, just use what's there).

Good idea, I didn't know about the `nginx_version` before.

**Comment by ADD-SP** [comment]
Thanks for your suggestion. This module is already compatible with the current Mainline NGINX, but considering that Mainline is still under development, there may be other compatibility issues in the future. So if in the future you encounter a compile error due to incompatibility with Mainline, it is recommended to reopen this issue unless necessary.
